export const LICENSE_SUGGESTIONS = [
  "MIT",
  "Apache-2.0",
  "GPL-3.0",
  "GPL-2.0",
  "AGPL-3.0",
  "LGPL-3.0",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "MPL-2.0",
  "ISC",
  "Unlicense",
  "CC0-1.0",
  "CC-BY-4.0",
  "EPL-2.0",
  "Artistic-2.0",
  "WTFPL",
  "Proprietary",
] as const;
