-- AlterTable
ALTER TABLE "Ad"
ADD COLUMN IF NOT EXISTS "isTargetedSidebar" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "targetThemeSlugs" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "targetPlatformSlugs" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

-- AlterTable
ALTER TABLE "AdConfig"
ADD COLUMN IF NOT EXISTS "targetingUnitPriceCents" INTEGER NOT NULL DEFAULT 0;
